//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IreneAdler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public System.Guid Contact_ID { get; set; }
        public System.DateTime Date_Added { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Land_Line { get; set; }
        public string Cell { get; set; }
        public string Email { get; set; }
    }
}
